api_key: phitjcdqg52u3ksh4ctan3alayaobfx3
cookie:
  expiry_days: 30
  key: Login
  name: hidro_web
credentials:
  usernames:
    josivaldo.barbosa:
      email: josivaldobombeiro@hotmail.com
      failed_login_attempts: 1
      first_name: Josivaldo
      last_name: Barbosa
      logged_in: false
      password: $2b$12$aXpvnYuzyBMJGQUdleGby.INzAIGa1iyVDicoetmocp2bzojVwEX6
      roles:
        - viewer
    kaua.lima:
      email: kauanrodrigoo25@gmail.com
      failed_login_attempts: 1
      first_name: Kauã
      last_name: Rodrigo
      logged_in: false
      password: $2b$12$i./.arsf/39qbmDYcHH24.X5M2E.xjUlHinh.AaPQNJ4wS3jzXP8i
      roles:
        - admin
        - editor
        - viewer